'use client';

import Link from 'next/link';

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-neutral-900 text-white">
      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="mb-8">
          <Link 
            href="/" 
            className="inline-flex items-center text-blue-400 hover:text-blue-300 mb-4"
          >
            ← Back to Gospel Study Assistant
          </Link>
          <h1 className="text-3xl font-bold text-white">Terms of Use</h1>
          <p className="text-neutral-400 mt-2">Effective Date: December 3, 2025</p>
        </div>

        <div className="prose prose-invert prose-blue max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="text-neutral-300 mb-4">
              By accessing and using the Gospel Study Assistant ("Service"), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">2. Purpose and Scope</h2>
            <p className="text-neutral-300 mb-4">
              The Gospel Study Assistant is designed to help users study and explore the scriptures and teachings of The Church of Jesus Christ of Latter-day Saints. This service provides AI-powered search and question-answering capabilities for educational and spiritual study purposes.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">3. Content and Sources</h2>
            <div className="text-neutral-300 mb-4 space-y-4">
              <p>Our content is sourced from:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>The Holy Scriptures (Book of Mormon, Bible, Doctrine & Covenants, Pearl of Great Price)</li>
                <li>General Conference talks and addresses</li>
                <li>Official Church publications and materials</li>
                <li>Come Follow Me curriculum</li>
              </ul>
              <p>
                All content is used for educational and non-commercial purposes. The Church of Jesus Christ of Latter-day Saints retains all rights to their published materials.
              </p>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">4. AI-Generated Responses</h2>
            <p className="text-neutral-300 mb-4">
              Responses provided by this service are generated by artificial intelligence and should be used for study and reflection purposes. While we strive for accuracy, AI responses may not always reflect official Church doctrine or teachings. For authoritative guidance, please consult:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-neutral-300 mb-4">
              <li>Official Church websites and publications</li>
              <li>Local Church leaders</li>
              <li>The scriptures themselves</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">5. User Responsibilities</h2>
            <p className="text-neutral-300 mb-4">Users agree to:</p>
            <ul className="list-disc pl-6 space-y-2 text-neutral-300 mb-4">
              <li>Use the service for lawful and appropriate purposes</li>
              <li>Not attempt to compromise the security or functionality of the service</li>
              <li>Respect the religious nature and intent of the content</li>
              <li>Not redistribute or republish content without proper authorization</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">6. Privacy and Data</h2>
            <p className="text-neutral-300 mb-4">
              We are committed to protecting your privacy. Questions and interactions with the service may be logged for improvement purposes. We do not sell personal information or share it with third parties except as necessary to provide the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-neutral-300 mb-4">
              This service is provided "as is" without warranties of any kind. We make no representations about the accuracy, completeness, or reliability of the AI-generated responses or the availability of the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
            <p className="text-neutral-300 mb-4">
              The creators and operators of this service shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">9. Changes to Terms</h2>
            <p className="text-neutral-300 mb-4">
              We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-white mb-4">10. Contact Information</h2>
            <p className="text-neutral-300 mb-4">
              For questions about these terms or the service, please contact us through the appropriate channels provided on our website.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}